
package net.felsing.client_cert.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2017-05-15T16:18:08.030+02:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "UserDataSourceException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class UserDataSourceException_Exception extends Exception {
    
    private net.felsing.client_cert.ejbca.UserDataSourceException userDataSourceException;

    public UserDataSourceException_Exception() {
        super();
    }
    
    public UserDataSourceException_Exception(String message) {
        super(message);
    }
    
    public UserDataSourceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UserDataSourceException_Exception(String message, net.felsing.client_cert.ejbca.UserDataSourceException userDataSourceException) {
        super(message);
        this.userDataSourceException = userDataSourceException;
    }

    public UserDataSourceException_Exception(String message, net.felsing.client_cert.ejbca.UserDataSourceException userDataSourceException, Throwable cause) {
        super(message, cause);
        this.userDataSourceException = userDataSourceException;
    }

    public net.felsing.client_cert.ejbca.UserDataSourceException getFaultInfo() {
        return this.userDataSourceException;
    }
}
